#!/bin/sh

set -e

rm -fr \
  tor-router_1.0* \
  tor-router/debian/files \
  tor-router/debian/tor-router/ \
  tor-router/debian/tor-router.substvars \
  tor-router/debian/tor-router.debhelper.log \
  tor-router/debian/.debhelper/

exit 0
