#!/bin/sh

# Tor-Router (network info script)
# Copyright (C) 2023 m4dm4x1337
#
# This file is part of the tor-router debian package.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

if ! command -v geoiplookup >/dev/null 2>&1; then
  echo "Please install geoiplookup: apt-get install geoip-bin" >&2
  exit 1
fi

wget -q -t1 -T5 -O- "https://check.torproject.org/torbulkexitlist" |
  xargs -r -n1 -P5000 geoiplookup |
    sed 's/GeoIP\s*Country\s*Edition:\s*//g; s/IP Address not found/ZZ, Unknown/g' |
      sort | uniq -c | sort -nr

exit $?
