#!/bin/sh

# Tor-Router (status detector script)
# Copyright (C) 2023 m4dm4x1337
#
# This file is part of the tor-router debian package.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

if [ "$(id -u)" != "0" ]; then
  echo "This script must be run as root" 1>&2
  exit 1
fi

if ! ip -4 route list 0/0 2>/dev/null | grep -oP 'dev \K\S+' >/dev/null 2>&1; then
  echo -n "offline"
else
  if ! iptables -nL TR_OUTPUT >/dev/null 2>&1; then
    echo -n "disabled"
  else
    if ! pgrep '^tor-router$' >/dev/null 2>&1; then
      echo -n "stopped"
    else
      echo -n "enabled"
    fi
  fi
fi

exit 0

