#!/bin/sh

# Tor-Router (up/down script)
# Copyright (C) 2023 m4dm4x1337
#
# This file is part of the tor-router debian package.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

SCRIPTPATH=$(readlink -f "$0")
SCRIPTNAME="${SCRIPTPATH##*/}"
SCRIPTDIR="${SCRIPTPATH%/*}"

# I18N
export TEXTDOMAINDIR=/usr/share/locale
export TEXTDOMAIN=tor-router

if [ "$(id -u)" != "0" ]; then
  echo "This script must be run as root" 1>&2
  exit 1
elif ! id -u debian-tor >/dev/null 2>&1; then
  echo "This script can not run if the user 'debian-tor' does not exist" 1>&2
  exit 2
fi

if [ -f /etc/default/tor-router ]; then
  . /etc/default/tor-router || true
fi

. $SCRIPTDIR/include/interfaces
. $SCRIPTDIR/include/ipset
. $SCRIPTDIR/include/iptables
. $SCRIPTDIR/include/iterator
. $SCRIPTDIR/include/networks
. $SCRIPTDIR/include/ports
. $SCRIPTDIR/include/routing
. $SCRIPTDIR/include/sysctl
. $SCRIPTDIR/include/torrc
. $SCRIPTDIR/include/tor-router

tor_router_up

exit $?
