#!/bin/sh

# Tor-Router (ipv4 detector script)
# Copyright (C) 2023 m4dm4x1337
#
# This file is part of the tor-router debian package.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

if ! command -v dig >/dev/null 2>&1; then
  echo "Please install dig: apt-get install dnsutils" >&2
  exit 1
fi

dig @208.67.222.222 \
    @208.67.220.220 \
    @208.67.222.220 \
    @208.67.220.222 \
    +short +tcp -4 -p 443 -t A \
    myip.opendns.com

#dig @resolver1.opendns.com \
#    @resolver2.opendns.com \
#    @resolver3.opendns.com \
#    @resolver4.opendns.com \
#    +short +tcp -4 -p 443 -t A \
#    myip.opendns.com

exit $?
